version: "3.7"

services:
  caddy:
    image: gh
    container_name: ghcr.io/wi4ad/caddy-compose
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ${CADDY_FILE}:/etc/caddy/Caddyfile
      - ${CADDY_DATA}:/data
      - ${CADDY_CONFIG}:/config